GET http://localhost:3000/ HTTP/1.1


########

POST http://localhost:3000/getAuthToken HTTP/1.1
Content-Type: application/json

{"Username" : "admin", "Password" : "admin"}

########

POST http://localhost:3000/createConfigFile HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImFkbWluIiwiUGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTU5MDgzODc2NiwiZXhwIjoxNTkwODQyMzY2fQ.F7tv0p2XASURHrech0FPM6QekH0h7hd-5KEutYhtUHE

{
  "address": "smtp.gmail.com",
  "username": "example@gmail.com",
  "password": "mysecretpassword",
  "port": 465
}

#######

GET http://localhost:3000/readConfigFile HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImFkbWluIiwiUGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTU5MDgzODc2NiwiZXhwIjoxNTkwODQyMzY2fQ.F7tv0p2XASURHrech0FPM6QekH0h7hd-5KEutYhtUHE


####

DELETE http://localhost:3000/deleteConfigFile HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImFkbWluIiwiUGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTU5MDgzODc2NiwiZXhwIjoxNTkwODQyMzY2fQ.F7tv0p2XASURHrech0FPM6QekH0h7hd-5KEutYhtUHE

#####

PUT http://localhost:3000/updateConfigFile HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImFkbWluIiwiUGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTU5MDgzODc2NiwiZXhwIjoxNTkwODQyMzY2fQ.F7tv0p2XASURHrech0FPM6QekH0h7hd-5KEutYhtUHE

{ "port" : 3000 , "password": "mysecretnewpassword"}